### ISSUE TITLE
New updated Raspberry Jame Mod for Minecraft PE.

### ISSUE THREAD

**Issue by ghost** [arpruss/raspberryjam-pe#2]
Hi, I read your instructable on how to do Python scripting in Minecraft PE and followed it. But as this instructable was somewhat outdated and the current version of QPython wasn't working with your Raspberry Jam Mod App, I took the liberty of copying all the scripts and modifying them for the new version of QPython. The modified version is now available here: https://github.com/cocodevienne/Python2MinecraftPE

I would appreciate any feedback from you and maybe you could update the RJM App.

**Comment by arpruss** [comment]
Thanks! What did you need to change?

**Comment by ghost** [comment]
I hadd to change the package name on lines 319-320 and the folder name of qpython line 326. Could you chnage it in the original and give me an honorable mention?

**Comment by ghost** [comment]
@arpruss

**Comment by arpruss** [comment]
I revised a bunch of stuff, including adding support for the new qpython and qpython3 (use /p3 for the latter).
